# Generated by Django 6.0.2 on 2026-02-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hareket Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Hareket Görseli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
