# Generated by Django 6.0.2 on 2026-02-17 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_video_url_alter_exercise_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personalworkout',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Coach Notes'),
        ),
        migrations.AlterField(
            model_name='personalworkout',
            name='reps',
            field=models.PositiveIntegerField(default=12, verbose_name='Reps'),
        ),
        migrations.AlterField(
            model_name='personalworkout',
            name='sets',
            field=models.PositiveIntegerField(default=3, verbose_name='Sets'),
        ),
        migrations.CreateModel(
            name='CoachQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Coach Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Plan Title (e.g., Cutting Phase)')),
                ('image', models.ImageField(upload_to='nutrition/', verbose_name='Diet Plan Image/PDF')),
                ('description', models.TextField(blank=True, verbose_name='Plan Details / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('weight', models.FloatField(verbose_name='Current Weight (kg)')),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='progress/', verbose_name='Front Photo')),
                ('photo_side', models.ImageField(blank=True, null=True, upload_to='progress/', verbose_name='Side Photo')),
                ('photo_back', models.ImageField(blank=True, null=True, upload_to='progress/', verbose_name='Back Photo')),
                ('notes', models.TextField(blank=True, verbose_name='User Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
