# Generated by Django 6.0.2 on 2026-02-17 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exercise_image_alter_personalworkout_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='image',
            field=models.ImageField(upload_to='nutrition/', verbose_name='Diet Plan Image'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Plan Title'),
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='progress/'),
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='progress/'),
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='photo_side',
            field=models.ImageField(blank=True, null=True, upload_to='progress/'),
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_done', models.PositiveIntegerField()),
                ('reps_done', models.PositiveIntegerField()),
                ('weight_done', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
